### ISSUE TITLE
Error compiling for board AI Thinker ESP32-CAM

### ISSUE THREAD

**Issue by jokikill** [Bodmer/TJpg_Decoder#29]
Hello,

I have an issue with the TJpg_Decoder on my esp32-cam code.

I tryed to create an IR vision on a tft screen, the ir is op but for the tft I have an error "...\Arduino\libraries\TJpg_Decoder-master\src/TJpg_Decoder.h:31:30: fatal error: LITTLEFS.h: No such file or directory for board AI Thinker ESP32-CAM".

For add a tft screen on my esp32-cam I followed this webpage : https://www.survivingwithandroid.com/esp32-cam-tft-display-picture-st7735/

Can you help me?

**Comment by alextief** [comment]
Hi Jokikill,
Im on the same Project like you. Try adding the fs.h library at the beginning (#include <fs.h>) or/and littlefs.h. 

But i cant compile because Bodmers TJpg_Decoder references BYTECLIP in some files and I cant get it to work...
"undefined reference to `BYTECLIP'"

**Comment by Bodmer** [comment]
@jokikill Which version of the Arduino ESP32 board package are you using? The latest is 2.0.1.

@jokikill BYTECLIP issue has been resolved.

**Comment by alextief** [comment]
> @jokikill Which version of the Arduino ESP32 board package are you using? The latest is 2.0.1.
> 
> @jokikill BYTECLIP issue has been resolved.

Ill will try it now if it works.
Anyways thank you very much for your work!!!

**Comment by Bodmer** [comment]
Looks like there was a change in 2.0.0  "Rename LITTLEFS to LittleFS to match ESP8266"....

https://github.com/espressif/arduino-esp32/commit/c8a4010f

**Comment by Bodmer** [comment]
I have renamed header file reference so the library will now only work on ESP32 with board package 2.0.0 or later.

**Comment by ajacobs-github** [comment]
When compiling for board ESP32S2 Dev Module I get the error undefined reference to `BYTECLIP' in tjpgd.c.  Arduino ESP32 version 2.0.1.  Board is sparkfun ESP32-S2 Thing Plus and display is Adafruit 2.8" TFT LCD shield with cap touch and micro SD

**Comment by Bodmer** [comment]
@ajacobs-github  This has been fixed in version 1.0.2 and should be available in the Arduino Libary manager soon.

**Comment by jokikill** [comment]
> Hi Jokikill, Im on the same Project like you. Try adding the fs.h library at the beginning (#include <fs.h>) or/and littlefs.h.
> 
> But i cant compile because Bodmers TJpg_Decoder references BYTECLIP in some files and I cant get it to work... "undefined reference to `BYTECLIP'"

I'm on the last update for it.

With the last update of Jpg_Decoder, I have always this error : 

In file included from ...\CamToIli9341\CamToIli9341.ino:21:0:
...\Arduino\libraries\TJpg_Decoder-master\src/TJpg_Decoder.h:23:26: fatal error: LittleFS.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board AI Thinker ESP32-CAM.

**Comment by jokikill** [comment]
I've switched on this tutorial for an ILI9341 https://blog.xuite.net/iamleon/blog/589421027

**Comment by pipi61** [comment]
try change
static uint8_t BYTECLIP (int val)
to
uint8_t BYTECLIP (int val)
in tjpgd.c

**Comment by Bodmer** [comment]
Interestingly the this simple change degrades rendering performance from 84ms to 99ms on the ESP32 for the Flash_Jpg example! So it is not an ideal change from that perspective for users that do not get the error (which seems to be specific to PlatformIO compilations, not the Arduino IDE ones).

**Comment by hiibrarahmad** [comment]
![image](https://user-images.githubusercontent.com/46841978/211074262-41f1b556-6cad-4a04-a1e4-a507eb5bc2ce.png)


> When compiling for board ESP32S2 Dev Module I get the error undefined reference to `BYTECLIP' in tjpgd.c. Arduino ESP32 version 2.0.1. Board is sparkfun ESP32-S2 Thing Plus and display is Adafruit 2.8" TFT LCD shield with cap touch and micro SD

try to add link like this it solve the issue in platform.io
![image](https://user-images.githubusercontent.com/46841978/211074364-0c7b9a04-cc16-43c8-ba81-a63abd21599d.png)
